---

- name: jenkins restart
  service: name=jenkins state=restarted
  become: yes
  
- name: jenkins update jobs
  command: "{{jenkins_home}}/jobs/job.sh {{item.item.name}}"
  become_user: "{{ jenkins_user }}"
  when: item.changed
  with_items: jenkins_jobs_changed.results

- name: jenkins reload configuration
  command: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{jenkins_prefix}} reload-configuration
  become_user: "{{ jenkins_user }}"

- name: nginx reload
  service: name=nginx state=reloaded
  become: yes
  
- name: apache restart
  service: name=apache2 state=restarted
  become: yes
  
